//   1 - " Partenerul este gata  "

//--------------------Coduri de la Slave la master--------------------//
// 101 - " Nu ai butoanele configurate  "
// 102 - " Incepem sa configuram butoanele  "
// 103 - " Ai butoane configurate  "
//     - " Daca doresti sa continui cu butoanele configurate, apasa 'Bine'  "
//     - " Daca doresti sa configurezi alta telecomanda apasa orice tasta  "
// 104 - " Ai pastrat configurarea butoanelor  "
// 105 - " Apasa o tasta pentru 'Bine'  "
// 106 - " Ai setat butonul 'Bine' "
// 107 - " Apasa o tasta pentru 'Anulare'  "
// 108 - " Ai setat butonul 'Anulare' "
// 109 - " Apasa o tasta pentru seta butonul `Inainte`  "
// 110 - " Ai setat butonul 'Inainte'  "
// 111 - " Apasa o tasta pentru seta butonul `Inapoi`  "
// 112 - " Ai setat butonul 'Inapoi'  "
// 113 - " Apasa o tasta pentru seta butonul `Stanga`  "
// 114 - " Ai setat butonul 'Stanga'  "
// 115 - " Apasa o tasta pentru seta butonul `Dreapta`  "
// 116 - " Ai setat butonul 'Dreapta'  "
// 117 - " Am primit un semnal  "
//     - " Apasa pe acelasi buton pentru a confirma  "
// 118 - " Nu a fost acelasi buton  "

// 150 - " Acesta tasta este deja utilizata  "
//     - " Te rog sa incerci din nou o alta tasta  " 
// 151 - " A intervenit o eroare  "
// 152 - " Mai incercam o data sa setam butonul "
